#!/usr/bin/env bash

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'a2n-s-gcal2org' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v TODO ]] && TODO=700
[[ ! -v WGET ]] && WGET="/usr/bin/wget"
[[ ! -v ICS2ORG ]] && ICS2ORG="$HOME/scripts/ical2org"
[[ ! -v ICSFILE ]] && ICSFILE="$HOME/org/sup.gcal"
[[ ! -v ORGFILE ]] && ORGFILE="$HOME/org/sup.org"
[[ ! -v URLFILE ]] && URLFILE="$HOME/scripts/.gcal2org.url"


usage () {
    #
    # the usage function.
    #
    echo "Usage: a2n-s-gcal2org [-h]"
    echo "Type -h or --help for the full help."
    exit 0
}


help () {
    #
    # the help function.
    #
    echo "a2n-s-gcal2org:"
    echo "     DEPRECATED."
    echo ""
    echo "Usage:"
    echo "     a2n-s-gcal2org [-h]"
    echo ""
    echo "Switches:"
    echo "     -h/--help             shows this help."
    echo ""
    echo "Environment variables:"
    echo "     WGET                  the program to download the calendar (defaults to \"/usr/bin/wget\")"
    echo "     ICS2ORG               the path to the conversion file (defaults to \"\$HOME/scripts/ical2org\")"
    echo "     ICSFILE               the path to the ICS file (defaults to \"\$HOME/org/sup.gcal\")"
    echo "     ORGFILE               the path to the ORG file (defaults to \"\$HOME/org/sup.org\")"
    echo "     URL                   the path to the secret google URL (defaults to \"\$HOME/scripts/.gcal2org.url\")"
    exit 0
}


main () {
    #
    # TODO.
    #
    while [[ $# -gt 0 ]]; do
    case "$1" in
        -h | --help )   help ;;
        -- ) shift; break ;;
        * ) break ;;
    esac
    done

    echo "THIS SCRIPT IS DEPRECATED."
    echo "Terminating..."
    exit 0
    URL="$(cat "$URLFILE")"
    $WGET -O $ICSFILE $URL
    $ICS2ORG < $ICSFILE > $ORGFILE
}


main "$@"
