#!/bin/sh
#
# Write/remove a task to do later.
#
# Select an existing entry to remove it from the file, or type a new entry to
# add it.

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-todo' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-todo [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-todo:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     amtoine-todo [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  file="$HOME/.todo"
  touch "$file"
  height=$(wc -l "$file" | awk '{print $1}')
  prompt="Add/delete a task: "

  cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
  while [ -n "$cmd" ]; do
      if grep -q "^$cmd\$" "$file"; then
          grep -v "^$cmd\$" "$file" > "$file.$$"
          mv "$file.$$" "$file"
          height=$(( height - 1 ))
      else
          echo "$cmd" >> "$file"
          height=$(( height + 1 ))
      fi

      cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
  done

  exit 0
}


main "$@"
