#!/bin/sh
#           ___                       personal page: https://a2n-s.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/a2n-s
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/a2n-s/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                _  __
#      __ _|_  )_ _ ___ ______| |/ _|_ _ _  _ _ _
#     / _` |/ /| ' \___(_-<___| |  _| '_| || | ' \
#     \__,_/___|_||_|  /__/   |_|_| |_|  \_,_|_||_|
#
# Description:  wrapper around lf to support advanced file preview with ueberzug.
#               creates cache files to make previews faster once computed one time.
# Dependencies: ueberzug
# License:      https://github.com/a2n-s/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine
#               gokcehan -> https://github.com/gokcehan/lf/wiki/Previews 

set -e

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'a2n-s-lfrun' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"


lfrun () {
  #
  # TODO.
  #
  if [ -n "$DISPLAY" ]; then
    export FIFO_UEBERZUG="${TMPDIR:-/tmp}/lf-ueberzug-$$"

    cleanup() {
      exec 3>&-
      rm "$FIFO_UEBERZUG"
    }

    mkfifo "$FIFO_UEBERZUG"
    ueberzug layer -s <"$FIFO_UEBERZUG" &
    exec 3>"$FIFO_UEBERZUG"
    trap cleanup EXIT

    if ! [ -d "$HOME/.cache/lf" ]; then
      mkdir -p "$HOME/.cache/lf"
    fi

    lf "$@" 3>&-
  else
    exec lf "$@"
  fi
}


usage () {
  #
  # the usage function.
  #
  echo "Usage: a2n-s-lfrun [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "a2n-s-lfrun:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     a2n-s-lfrun [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  lfrun "$@"
}


main "$@"
