#! /bin/bash
#           ___                       personal page: https://a2n-s.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/a2n-s
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/a2n-s/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                          _
#      __ _|_  )_ _ ___ ______ _  _ _ __| |
#     / _` |/ /| ' \___(_-<___| || | '_ \ |
#     \__,_/___|_||_|  /__/    \_,_| .__/_|
#                                  |_|
#
# Description:  updates some lists of installed packages.
# Dependencies: pacman, comm
# License:      https://github.com/a2n-s/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'a2n-s-upl' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"


usage () {
  #
  # the usage function.
  #
  echo "Usage: a2n-s-upl [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "a2n-s-upl:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     a2n-s-upl [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  dir="$HOME/.pkgslists"
  echo "updating packages list..."
    pacman -Qqe > $dir/allpkglist.txt
    pacman -Qqent > $dir/pkglist.txt
  echo "updating dependencies list..."
    comm -13 <(pacman -Qqdt | sort) <(pacman -Qqdtt | sort) > $dir/optdeplist.txt
  echo "updating foreign packages list..."
    pacman -Qqem > $dir/foreignpkglist.txt
  echo "updating cargo commands list..."
    cargo --list > $dir/cargocmdlist.txt
  echo "updating python packages list..."
    /usr/bin/pip list > $dir/pippkglist.txt
  echo "all done!"
}


main "$@"
