#!/usr/bin/env bash
#           ___                       personal page: https://a2n-s.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/a2n-s
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/a2n-s/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                _     __
#      __ _|_  )_ _ ___ ______| |__ / _|__ _
#     / _` |/ /| ' \___(_-<___| / _|  _/ _` |
#     \__,_/___|_||_|  /__/   |_\__|_| \__, |
#                                      |___/
#
# Description:  a wrapper around lazygit to use it from anywhere on the dotfiles.
# Dependencies:
# License:      https://github.com/a2n-s/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'a2n-s-lcfg' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to modufy environment variables
[[ ! -v GIT_DIR ]] && GIT_DIR="$HOME/.dotfiles"
[[ ! -v WORK_TREE ]] && WORK_TREE="$HOME"

usage () {
  #
  # the usage function.
  #
  echo "Usage: a2n-s-lcfg [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "a2n-s-lcfg:"
  echo "     open the dotfiles *bare* \`git\` repository in \`lazygit\`."
  echo ""
  echo "Usage:"
  echo "     a2n-s-lcfg [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     GIT_DIR               the path to the \`git\` directory, i.e. the bare equivalent of the \`.git\` directory (defaults to \"\$HOME/.dotfiles\")"
  echo "     WORK_TREE             the path to the working tree of the dotfiles, i.e. where the files are tracked (defaults to \"\$HOME\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help ) help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  /usr/bin/lazygit --git-dir="$GIT_DIR" --work-tree="$WORK_TREE"
}


main "$@"
