#! /usr/bin/bash
#           ___                       personal page: https://amtoine.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/amtoine
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/amtoine/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                _       __
#      __ _|_  )_ _ ___ ______| |_ __ / _|__ _
#     / _` |/ /| ' \___(_-<___|  _/ _|  _/ _` |
#     \__,_/___|_||_|  /__/    \__\__|_| \__, |
#                                        |___/
#
# Description:  a wrapper around tig to use it from anywhere on the dotfiles.
# Dependencies:
# License:      https://github.com/amtoine/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-tcfg' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v GIT_DIR ]] && GIT_DIR="$HOME/.dotfiles"
[[ ! -v WORK_TREE ]] && WORK_TREE="$HOME"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-tcfg [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-tcfg:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     amtoine-tcfg [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     GIT_DIR               the path to the \`git\` directory, i.e. the bare equivalent of the \`.git\` directory (defaults to \"\$HOME/.dotfiles\")"
  echo "     WORK_TREE             the path to the working tree of the dotfiles, i.e. where the files are tracked (defaults to \"\$HOME\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  GIT_DIR="$GIT_DIR" GIT_WORK_TREE="$WORK_TREE" tig --all
}


main "$@"
