#! /usr/bin/bash
#           ___                       personal page: https://a2n-s.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/a2n-s
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/a2n-s/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                            _ _
#      __ _|_  )_ _ ___ ______ __ _ _ _ __| | |__
#     / _` |/ /| ' \___(_-<___/ _` | '_/ _` | '_ \
#     \__,_/___|_||_|  /__/   \__, |_| \__,_|_.__/
#                             |___/
#
# Description:  rename the default branch automaticcaly.
#               By default, rename master into main on the remote origin.
#               The above can be changed with `OLD=<old-branch> NEW=<new-branch> REM=<remote> a2n-s-grdb`
# Dependencies: git
# License:      https://github.com/a2n-s/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

[[ ! -v OLD ]] && OLD="master"
[[ ! -v NEW ]] && NEW="main"
[[ ! -v REM ]] && REM="origin"

echo "$REM: $OLD -> $NEW"

git branch -m "$OLD" "$NEW"
git fetch "$REM" -p
git branch -u "$REM"/"$NEW" "$NEW"
git remote set-head "$REM" -a
