#!/usr/bin/env bash
#           ___                       personal page: https://amtoine.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/amtoine
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/amtoine/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                                  _        _
#      __ _|_  )_ _ ___ ______ ____  _ ______ __| |_ __ _| |_ ___
#     / _` |/ /| ' \___(_-<___(_-< || (_-<___(_-<  _/ _` |  _(_-<
#     \__,_/___|_||_|  /__/   /__/\_, /__/   /__/\__\__,_|\__/__/
#                                 |__/
#
# Description:  show some system information.
# Dependencies: sensors, grep, awk, free, top.
# License:      https://github.com/amtoine/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-sys-stats' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v ICONS ]] && ICONS="/usr/share/icons/amtoine-icons-git/dark/128x128"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-sys-stats [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-sys-stats:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     amtoine-sys-stats [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     ICONS                 TODO (defaults to \"/usr/share/icons/amtoine-icons-git/dark/128x128\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  dunstify "amtoine-sys-stats" "polling the system for information..." --icon="$ICONS/misc/gears.png"

  memory=$(free -m | awk 'NR==2{printf "%s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }')
  load=$(top -bn1 | grep load | awk '{printf "%.2f\n", $(NF-2)}')
  cpu_temp=$(sensors | grep 'Core .:' | awk -F' ' '{ print $3 }')

  dunstify "Usage" "$memory" --icon="$ICONS/misc/usage-chart.png"
  dunstify "Load" "$load" --icon="$ICONS/misc/brain-machine.png"
  dunstify "CPU" "$cpu_temp" --icon="$ICONS/misc/temperature.png"
}


main "$@"
