#!/usr/bin/env bash
#           ___                       personal page: https://a2n-s.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/a2n-s
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/a2n-s/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                _   _                  _      _
#      __ _|_  )_ _ ___ ______| |_(_)_ __  ___ ___ __| |__ _| |_ ___
#     / _` |/ /| ' \___(_-<___|  _| | '  \/ -_)___/ _` / _` |  _/ -_)
#     \__,_/___|_||_|  /__/    \__|_|_|_|_\___|   \__,_\__,_|\__\___|
#
# Description:  show the date and the time in a notification.
# Dependencies: date.
# License:      https://github.com/a2n-s/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'a2n-s-TODO' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v ICONS ]] && ICONS="/usr/share/icons/a2n-s-icons"


usage () {
  #
  # the usage function.
  #
  echo "Usage: a2n-s-time-date [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "a2n-s-time-date:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     a2n-s-time-date [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     ICONS                 TODO (defaults to \"/usr/share/icons/a2n-s-icons\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  notify-send -t 3500 "$(date '+%a %b %e%n%r')" --icon="$ICONS/calendar.png"
}


main "$@"
