#!/usr/bin/env bash

OPTIONS=$(getopt -o h --long help -n 'a2n-s-apply-theme' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# environment variables.
[ -z "$COMMENT_SYMBOL" ] && COMMENT_SYMBOL="#"

# some constants.
BEGIN_MARKER="$COMMENT_SYMBOL+ BEGIN"
END_MARKER="$COMMENT_SYMBOL+ END"
FORMAT_MARKER="$COMMENT_SYMBOL+ format"
NAMES_MARKER="$COMMENT_SYMBOL+ names"
TEMP_MARKER="%%%"  # a temporary marker to ensure blank characters are taken into account.

MISSING_MARKER_ERROR_CODE=1
MISPLACED_MARKERS_ERROR_CODE=2
MISSING_FIELD_ERROR_CODE=3
BAD_ARGUMENTS_ERROR_CODE=4
ARRAY_SIZE_MISMATCH_ERROR_CODE=5


terminate () {
    echo "Terminating..." > /dev/stderr;
    exit "$1";
}


assert_file_exist () {
    [ ! -f "$1" ] && {
        echo "$0: '$1': No such file or directory" > /dev/stderr;
        terminate "$BAD_ARGUMENTS_ERROR_CODE";
    }
}


check_markers () {
    local theme_file=$1
    local name=$2
    # assert color-theme markers exist.
    local begin_markers=($(grep "^$BEGIN_MARKER:$name$" "$theme_file" -n | awk -F: '{print $1}'))
    local end_markers=($(grep "^$END_MARKER:$name$" "$theme_file" -n | awk -F: '{print $1}'))
    [ "${#begin_markers[@]}" -ne 1 ] && {
        echo "There should be exactly 1 '$BEGIN_MARKER:$name' marker in '$theme_file'." > /dev/stderr;
        echo "Got ${#begin_markers[@]} markers on lines ${begin_markers[*]}." > /dev/stderr;
        terminate "$MISSING_MARKER_ERROR_CODE";
    }
    [ "${#end_markers[@]}" -ne 1 ] && {
        echo "There should be exactly 1 '$END_MARKER:$name' marker in '$theme_file'." > /dev/stderr;
        echo "Got ${#end_markers[@]} markers on lines ${end_markers[*]}." > /dev/stderr;
        terminate "$MISSING_MARKER_ERROR_CODE";
    }

    # assert color-theme markers are placed correctly.
    local line_begin_marker=${begin_markers[0]}
    local line_end_marker=${end_markers[0]}
    [ "$line_begin_marker" -gt "$line_end_marker" ] && {
        echo "The '$END_MARKER:$name' marker should come after '$BEGIN_MARKER:$name'." > /dev/stderr;
        echo "'$END_MARKER:$name' found on line $line_end_marker" > /dev/stderr;
        echo "'$BEGIN_MARKER:$name' found on line $line_begin_marker" > /dev/stderr;
        terminate "$MISPLACED_MARKERS_ERROR_CODE";
    }

    echo "$line_begin_marker" "$line_end_marker"
}


# extract meta data from the color-theme marker
get_marker_zone () {
  sed -n "/^$BEGIN_MARKER:$2$/,/^$END_MARKER:$2$/p" "$1"
}


check_format () {
    local line_begin_marker=$1
    local line_end_marker=$2
    local theme_file=$3
    local format=$4

    [ -z "$format" ] && {
        echo "No format found between lines $line_begin_marker and $line_end_marker of $theme_file..." > /dev/stderr;
        echo "Please make sur the '$FORMAT_MARKER' field is correct." > /dev/stderr;
        terminate "$MISSING_FIELD_ERROR_CODE";
    }
    [ -z "$(echo "$format" | grep "{name}" )" ] && {
        echo "missing 'name' key in format '$format' between lines $line_begin_marker and $line_end_marker of $theme_file..." > /dev/stderr;
        terminate "$MISSING_FIELD_ERROR_CODE";
    }
    [ -z "$(echo "$format" | grep "{color}" )" ] && {
        echo "missing 'color' key in format '$format' between lines $line_begin_marker and $line_end_marker of $theme_file..." > /dev/stderr;
        terminate "$MISSING_FIELD_ERROR_CODE";
    }
}


get_format_from_marker_zone () {
    local format=$(echo "$1" | grep "^$FORMAT_MARKER:.*" | cut -d: -f2-)
    check_format "$2" "$3" "$4" "$format"

    echo "$format"
}


get_names_from_marker_zone () {
    local names=()
    names=($(echo "$marker_zone" | grep "^$NAMES_MARKER:.*" | awk -F: '{print $2}' | tr ',' ' '))
    [ "${#names[@]}" -eq 0 ] && {
        echo "No names found between lines $line_begin_marker and $line_end_marker of $theme_file..." > /dev/stderr;
        echo "Please make sur the '$NAMES_MARKER' field is correct." > /dev/stderr;
        terminate "$MISSING_FIELD_ERROR_CODE";
    }
    echo "${names[@]}"
}


assert_name_and_color_sizes () {
    [ "$1" -ne "$2" ] && {
        echo "Not the same number of colors and names..." > /dev/stderr;
        echo "Computed $1 colors." > /dev/stderr;
        echo "Found $2 names in $3". > /dev/stderr;
        terminate "$ARRAY_SIZE_MISMATCH_ERROR_CODE";
    }
    return 0
}


apply_palette_to_hunk () {
    theme_file=$1
    name=$2
    shift 2
    palette=($@)

    res=$(check_markers "$theme_file" "$name")
    code=$?
    [ $code -ne 0 ] && return "$code"
    line_begin_marker=$(echo "$res" | cut -d' ' -f1)
    line_end_marker=$(echo "$res" | cut -d' ' -f2)

    marker_zone=$(get_marker_zone "$theme_file" "$name")
    code=$?
    [ $code -ne 0 ] && return "$code"

    format=$(get_format_from_marker_zone "$marker_zone" "$line_begin_marker" "$line_end_marker" "$theme_file")
    code=$?
    [ $code -ne 0 ] && return "$code"
    names=($(get_names_from_marker_zone "$marker_zone" "$line_begin_marker" "$line_end_marker" "$theme_file"))
    code=$?
    [ $code -ne 0 ] && return "$code"

    assert_name_and_color_sizes "${#palette[@]}" "${#names[@]}" "$theme_file"
    code=$?
    [ $code -ne 0 ] && return "$code"

    # remove the colors inbetween the markers.
    file_no_colors=$(sed -e "/^$BEGIN_MARKER:$name$/,/^$END_MARKER:$name$/{//!d}" "$theme_file")
    # add the colors.
    for ((i=(("${#palette[@]}"-1)); i>=0; i--)) ;
    do
        line=$(echo "$format" | sed -e "s/{name}/${names[$i]}/g" -e "s/{color}/${palette[$i]}/g")
        file_no_colors=$(echo "$file_no_colors" | sed "/^$BEGIN_MARKER:$name/a $TEMP_MARKER$line" | sed "s/^$TEMP_MARKER//")
    done
    # add the fields back.
    file_no_colors=$(echo "$file_no_colors" | sed "/^$BEGIN_MARKER:$name/a $NAMES_MARKER:$(echo "${names[*]}" | tr ' ' ',')")
    file_no_colors=$(echo "$file_no_colors" | sed "/^$BEGIN_MARKER:$name/a $FORMAT_MARKER:$format")
    echo "$file_no_colors" > "$theme_file"
}


apply_theme() {
    theme_file="$1"
    shift 1

    assert_file_exist "$theme_file"

    declare -A palettes
    for arg in "$@";
    do
      name=$(echo "$arg" | cut -d= -f1)
      value=$(echo "$arg" | cut -d= -f2)
      palettes["$name"]="$value"
    done

    for name in "${!palettes[@]}";
    do
        apply_palette_to_hunk "$theme_file" "$name" "${palettes[$name]}"
    done
}


usage () {
  #
  # the usage function.
  #
  echo "Usage: a2n-s-apply-theme [-h] CONFIG_FILE COLOR_PALETTE"
  echo "Type -h or --help for the full help."
}


help () {
  #
  # the help function.
  #
  echo "a2n-s-apply-theme:"
  echo "     This script allows the user to easily apply a theme to a config file."
  echo "     Do not forget to put it in your PATH."
  echo ""
  echo "Usage:"
  echo "     a2n-s-apply-theme [-h] CONFIG_FILE COLOR_PALETTE"
  echo ""
  echo "          - CONFIG_FILE is the path to the config file to edit"
  echo "          - COLOR_PALETTE is the list of colors to apply to the config file"
  echo ""
  echo "Switches:"
  echo "     -h/--help               shows this help."
  echo ""
  echo "Environment variables:"
  echo "     COMMENT_SYMBOL          the symbol used to begin comment in the config file (defaults to '#', e.g. for \`bash\` or \`python\`)"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help ) help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  [ -z "$1" ] && {
      echo "no file to edit given as first positional argument...";
      usage;
      exit "$BAD_ARGUMENTS_ERROR_CODE";
  }
  [ -z "$2" ] && {
      echo "no colors to apply given as second positional argument...";
      usage;
      exit "$BAD_ARGUMENTS_ERROR_CODE";
  }

  file=$1
  shift 1
  apply_theme "$file" "$@"
}


main "$@"
