#! /usr/bin/bash
#           ___                       personal page: https://amtoine.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/amtoine
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/amtoine/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                _             _   _
#      __ _|_  )_ _ ___ ______| |_ ___  __ _| |_| |__
#     / _` |/ /| ' \___(_-<___|  _/ _ \/ _` | / / '_ \
#     \__,_/___|_||_|  /__/    \__\___/\__, |_\_\_.__/
#                                      |___/
#
# Description:  toggles the keyboard layout between qwerty and azerty.
# Dependencies: setxkbmap 
# License:      https://github.com/amtoine/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-togkb' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-togkb [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-togkb:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     amtoine-togkb [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  if [[ $(setxkbmap -query | grep layout | sed "s/layout:\s\+\(.*\)/\1/") = fr ]]; then
    setxkbmap -layout us;
  elif [[ $(setxkbmap -query | grep layout | sed "s/layout:\s\+\(.*\)/\1/") = us ]]; then
    setxkbmap -layout fr;
  fi
}


main "$@"
