#! /usr/bin/bash
#           ___                       personal page: https://a2n-s.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/a2n-s
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/a2n-s/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                   _
#      __ _|_  )_ _ ___ ______ __| |_ __  _ _ _  _ _ _
#     / _` |/ /| ' \___(_-<___/ _` | '  \| '_| || | ' \
#     \__,_/___|_||_|  /__/   \__,_|_|_|_|_|  \_,_|_||_|
#
# Description:  wrapper around dmenu_run to launch dmenu in the middle and in a grid fashion.
# Dependencies: dmenu
# License:      https://github.com/a2n-s/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'a2n-s-dmrun' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v DMWIDTH ]] && DMWIDTH=700
[[ ! -v DMHEIGHT ]] && DMHEIGHT=10
[[ ! -v DMCOLUMNS ]] && DMCOLUMNS=3
[[ ! -v DMLINES ]] && DMLINES=9
[[ ! -v DMBORDER ]] && DMBORDER=5


usage () {
  #
  # the usage function.
  #
  echo "Usage: a2n-s-dmrun [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "a2n-s-dmrun:"
  echo "     a wrapper around dmenu_run, with some extra flags to make it prettier."
  echo ""
  echo "Usage:"
  echo "     a2n-s-dmrun [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     DMWIDTH               the width of the \`dmenu\` window (defaults to 700)"
  echo "     DMHEIGHT              the height of the \`dmenu\` window (defaults to 10)"
  echo "     DMCOLUMNS             the number of columns in the \`dmenu\` window (defaults to 3)"
  echo "     DMLINES               the number of lines in the \`dmenu\` window (defaults to 9)"
  echo "     DMBORDER              the width of the border of the \`dmenu\` window (defaults to 5)"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  dmenu_run -g $DMCOLUMNS -l $DMLINES \
            -x $((960 - $DMWIDTH/2)) -y $((540 - ($DMLINES+1)*$DMHEIGHT/2)) \
            -z $DMWIDTH -h $DMHEIGHT -bw $DMBORDER -fn "mononoki Nerd Font-20"
}


main "$@"
