#! /usr/bin/bash
#           ___                       personal page: https://amtoine.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/amtoine
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/amtoine/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                   _         _
#      __ _|_  )_ _ ___ ______ __| |___  __| |__
#     / _` |/ /| ' \___(_-<___(_-< / _ \/ _| / /
#     \__,_/___|_||_|  /__/   /__/_\___/\__|_\_\
#
# Description:  a wrapper for slock which prints a fancy raibow cow on the lock screen.
# Dependencies: cowsay, fortune, locat.
# License:      https://github.com/amtoine/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-slock' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-slock [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-slock:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     amtoine-slock [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  # slock -m "$(cowsay $(fortune -c) | lolcat -ft)"
  # slock -m "$(figlet -tcf slant "Screen Is Locked. Type Your Password To Unlock." -w 100)"
  # slock -m "$(figlet -tcf slant "Screen Is Locked. Type Your Password To Unlock." -w 100 | lolcat -ft)"
  # slock -m "$(figlet -tf small "Bet you can't crack it open.")"
  slock -m ""
}


main "$@"
