#!/usr/bin/env python3
#           ___                       personal page: https://amtoine.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/amtoine
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/amtoine/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                _
#      __ _|_  )_ _ ___ ______| |_ __
#     / _` |/ /| ' \___(_-<___| | '  \
#     \__,_/___|_||_|  /__/   |_|_|_|_|
#
# Description:  prints the list of connected monitors with their positions and geometries.
#               inspired by https://askubuntu.com/questions/639495/how-can-i-list-connected-monitors-with-xrandr
# Dependencies: gi module
# License:      https://github.com/amtoine/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

import gi
gi.require_version("Gdk", "3.0")
from gi.repository import Gdk
import argparse


def fetch_monitors():
    """TODO."""
    allmonitors = []

    gdkdsp = Gdk.Display.get_default()
    for i in range(gdkdsp.get_n_monitors()):
        monitor = gdkdsp.get_monitor(i)
        scale = monitor.get_scale_factor()
        geo = monitor.get_geometry()
        allmonitors.append([
            monitor.get_model()] + [n * scale for n in [
                geo.x, geo.y, geo.width, geo.height
            ]
        ])

    print(allmonitors)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    args = parser.parse_args()
    fetch_monitors()
