#!/bin/sh
#           ___                       personal page: https://a2n-s.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/a2n-s
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/a2n-s/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                             __
#      __ _|_  )_ _ ___ ______ ____  _ _ _ / _|___ ___ _ __  ___ _ _
#     / _` |/ /| ' \___(_-<___(_-< || | '_|  _|___/ _ \ '_ \/ -_) ' \
#     \__,_/___|_||_|  /__/   /__/\_,_|_| |_|     \___/ .__/\___|_||_|
#                                                     |_|
#
# Description:  opens a link or the default homepage in surf tabbed.
# Dependencies: tabbed, surf
# License:      https://github.com/a2n-s/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine


# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'a2n-s-surf-open' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v XIDFILE ]] && XIDFILE="/tmp/tabbed-surf.xid"
[[ ! -v URI ]] && URI="file:///home/ants/.config/surf/html/homepage.html"


usage () {
  #
  # the usage function.
  #
  echo "Usage: a2n-s-surf-open [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "a2n-s-surf-open:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     a2n-s-surf-open [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     XIDFILE               TODO (defaults to \"/tmp/tabbed-surf.xid\")"
  echo "     URI                   TODO (defaults to \"file:///home/ants/.config/surf/html/homepage.html\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  [ -f $XIDFILE ] && pidof surf || rm $XIDFILE

  if [ "$#" -gt 0 ];
  then
	  URI="$1"
  fi

  runtabbed() {
	  tabbed -dcn tabbed-surf -r 2 surf -e '' "$URI" >"$XIDFILE" \
		  2>/dev/null &
  }

  if [ ! -r "$XIDFILE" ];
  then
	  runtabbed
  else
	  xid=$(cat "$XIDFILE")
	  xprop -id "$xid" >/dev/null 2>&1
	  if [ $? -gt 0 ];
	  then
		  runtabbed
	  else
		  surf -e "$xid" "$URI" >/dev/null 2>&1 &
	  fi
  fi
}


main "$@"
