#!/bin/sh
#*
#*                 _    __ _ _
#*  __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#* / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS: https://github.com/goatfiles
#* \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#* |___/
#*


# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-surf-open' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v XIDFILE ]] && XIDFILE="/tmp/tabbed-surf.xid"
[[ ! -v URI ]] && URI="file:///home/ants/.config/surf/html/homepage.html"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-surf-open [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-surf-open:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     amtoine-surf-open [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     XIDFILE               TODO (defaults to \"/tmp/tabbed-surf.xid\")"
  echo "     URI                   TODO (defaults to \"file:///home/ants/.config/surf/html/homepage.html\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  [ -f $XIDFILE ] && pidof surf || rm $XIDFILE

  if [ "$#" -gt 0 ];
  then
	  URI="$1"
  fi

  runtabbed() {
	  tabbed -dcn tabbed-surf -r 2 surf -e '' "$URI" >"$XIDFILE" \
		  2>/dev/null &
  }

  if [ ! -r "$XIDFILE" ];
  then
	  runtabbed
  else
	  xid=$(cat "$XIDFILE")
	  xprop -id "$xid" >/dev/null 2>&1
	  if [ $? -gt 0 ];
	  then
		  runtabbed
	  else
		  surf -e "$xid" "$URI" >/dev/null 2>&1 &
	  fi
  fi
}


main "$@"
