#!/usr/bin/env bash
#*
#*                 _    __ _ _
#*  __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#* / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS: https://github.com/goatfiles
#* \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#* |___/
#*

# parse the arguments
OPTIONS=$(getopt -o hcp --long help,check,print -n 'amtoine-battery' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[ -z "$BATTERY" ] && BATTERY="BAT0"
[ -z "$LOW" ] && LOW=15
[ -z "$HIGH" ] && HIGH=85
[ -z "$ICONS" ] && ICONS="/usr/share/icons/amtoine-icons-git/stickers/100x100"
[ -z "$DUNST_ID" ] && DUNST_ID=1

# the location of the battery information files
SUPPLY="/sys/class/power_supply"


_get_battery_status() {
    # Compute the status of the battery.
    #
    # Args:
    #   $1 (str): the name of the battery.
    #
    # Returns:
    #   status (str): the status of the battery BAT0.
    status="$(cat "$SUPPLY/$1/status")"
    echo "$status"
}


_get_battery_level() {
    # Compute the level of the battery.
    #
    # Args:
    #   $1 (str): the name of the battery.
    #
    # Returns:
    #   stat (int): the level of the battery BAT0.
    level="$(cat "$SUPPLY/$1/capacity")"
    echo "$level"
}


_check_battery_state() {
    # Check the state of the battery.
    #
    # The battery is considered:
    #   - "low" when discharging and below the "$LOW" bound.
    #   - "high" when charging and above the "$HIGH" bound.
    #
    # Args:
    #   $1 (str): the status of the battery.
    #   $2 (str): the level of the battery.
    #
    # Returns:
    #   state (str): the general state of the battery, i.e. either "low",
    #       "high" or empty, which means the state should be considered ok.
    status="$1"
    level="$2"
    if [ "$status" = "Discharging" ] && [ "$level" -le "$LOW" ]; then
        state="low"
    elif [ "$level" -ge "$HIGH" ]; then
        if [ "$status" = "Not Charging" ] || [ "$status" = "Charging" ]; then
            state="high"
        fi
    fi
    echo "$state"
}


_get_icon_name () {
    # Get the icon name based on the status and the level.
    #
    # Args:
    #   $1: the status of the battery.
    #   $2: the level of the battery.
    status="$1"
    if [ "$status" == "Charging" ]; then
        dir="charging"
    else
        dir="normal"
    fi

    level="$2"
    name="$((level / 10))0"
    if [ "$level" -ne 100 ]; then
        name="0$name"
    fi

    echo "$dir/level-$name.png"
}


print_battery () {
    # Print the state of the battery in a notification.
    #
    # Args:
    #   $1: the status of the battery.
    #   $2: the level of the battery.
    status="$1"
    level="$2"

    icon=$(_get_icon_name "$status" "$level")

    dunstify --urgency low "amtoine-battery" "$BATTERY is $status at $level" --icon="$ICONS/battery/$icon" --timeout 5000 --replace="$DUNST_ID"
}


check_battery () {
    # Check the battery and throw notifications if needed.
    # get the status and the level of the battery.
    status=$(_get_battery_status "$BATTERY")
    level=$(_get_battery_level "$BATTERY")
    echo "status: $status"
    echo "level: $level"

    state="$(_check_battery_state "$status" "$level")"

    # throw a notification only if required.
    if [ -n "$state" ]; then
        icon=$(_get_icon_name "$status" "$level")
        dunstify --urgency critical "amtoine-battery" "$BATTERY is $state\n($status at $level%)" --icon="$ICONS/battery/$icon" --replace="$DUNST_ID";
    else
        dunstify --close="$DUNST_ID";
    fi
}


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-battery [-hcp]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-battery:"
  echo "     a script to check the state of the battery and throw appropriate notifications."
  echo ""
  echo "     run \`sudo systemctl enable cronie\` to activate the \`cron\` daemon if not already done, then"
  echo "     add \`* * * * * DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=<address> /usr/local/bin/amtoine-battery --check\`"
  echo "     to the \`cron\` table with \`crontab -e\` and restart the \`cron\` daemon with"
  echo "     \`sudo systemctl restart cronie\`. The address can be found with \`echo \$DBUS_SESSION_BUS_ADDRESS\`."
  echo ""
  echo "Usage:"
  echo "     amtoine-battery [-hcp]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo "     -p/--print            print the state of the battery in a notification and exit."
  echo "     -c/--check            check the state of the battery and throw a notification if critical."
  echo ""
  echo "Environment variables:"
  echo "     BATTERY               the name of the battery to check, inside '/sys/class/power_supply'(defaults to 'BAT0')"
  echo "     LOW                   the threshold below which a discharging battery is considered critical (defaults to 15)"
  echo "     HIGH                  the threshold above which a charging battery is considered critical (defaults to 85)"
  echo "     ICONS                 the path the the icons (defaults to '/usr/share/icons/amtoine-icons-git/dark/128x128')"
  echo "     DUNST_ID              the id of the sound notification, to replace them properly (defaults to 1)"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -c | --check )  ACTION="check"; shift 1 ;;
      -p | --print )  ACTION="print"; shift 1 ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  # an action is required
  [ -z "$ACTION" ] && usage
  case "$ACTION" in
    check ) check_battery ;;
    print ) print_battery "$(_get_battery_status "$BATTERY")" "$(_get_battery_level "$BATTERY")" ;;
    * ) echo "an error occured (got unexpected '$ACTION')"; exit 1 ;;
  esac
}


main "$@"
