#! /usr/bin/bash

export FZF_DEFAULT_OPTS='
--height=100%
--layout=reverse
--prompt="Manual: "
--preview="echo {1} | sed -E \"s/^\((.+)\)/\1/\" | xargs -I{S} man -Pcat {S} {2} 2>/dev/null"'


help () {
  #
  # the help function.
  #
  echo "amtoine-macho:"
  echo "     This script allows the user to easily search man pages with fzf."
  echo "     Do not forget to puth it in your PATH."
  echo ""
  echo "Usage:"
  echo "     amtoine-macho [-h] [-s SECTION]"
  echo ""
  echo "Switches:"
  echo "     -h         show this help."
  echo "     -s         select a particular section to search from amongst man pages."
  exit 0
}


main () {
  #
  # TODO.
  #
  while getopts ":s:h" opt; do
      case "$opt" in
          h ) help;;
          s ) SECTION=$OPTARG; shift 2;;
          \?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
          : ) echo "Option -$OPTARG requires an argument" >&2; exit 1;;
      esac
  done

  manual=$(apropos -s ${SECTION:-''} ${@:-.} | \
    grep -v -E '^.+ \(0\)' |\
    awk '{print $2 "    " $1}' | \
    sort | \
    fzf | \
    sed 's/^(.*)\s\+//' \
  )

  [ -z "$manual" ] && exit 0
  man "$manual"
}


main "$@"
