#! /bin/bash
#           ___                       personal page: https://amtoine.github.io/
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/amtoine
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/amtoine/dotfiles
#     \__,_/___|_||_|       /__/
#           ___                          _
#      __ _|_  )_ _ ___ ______ _  _ _ __| |
#     / _` |/ /| ' \___(_-<___| || | '_ \ |
#     \__,_/___|_||_|  /__/    \_,_| .__/_|
#                                  |_|
#
# Description:  updates some lists of installed packages.
# Dependencies: pacman, comm
# License:      https://github.com/amtoine/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# the environment variables.
[ -z "$DIR" ] && DIR="$HOME/.pkgs"


# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-upl' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-upl [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-upl:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     amtoine-upl [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     DIR                   the output directory to dump the lists to (defaults to \`$HOME/.pkgs\`)."
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  [ ! -d "$DIR" ] && {
    echo "creating $DIR"
    mkdir -p "$DIR"
  }

  echo "updating packages list..."
    pacman -Qe > "$DIR/all.pacman"
    pacman -Qen > "$DIR/native.pacman"
  echo "updating dependencies list..."
    comm -13 <(pacman -Qdt | sort) <(pacman -Qdtt | sort) > "$DIR/opt.pacman"
  echo "updating foreign packages list..."
    pacman -Qem > "$DIR/foreign.pacman"

  echo "updating cargo commands list..."
    cargo install --list > "$DIR/pkgs.cargo"

  echo "updating python packages list..."
    /usr/bin/pip list > "$DIR/pkgs.pip"
    /usr/bin/pipx list > "$DIR/pkgs.pipx"

  echo "all done!"
}


main "$@"
