#! /usr/bin/bash

# parse the arguments.
OPTIONS=$(getopt -o h --long help -n 'amtoine-open' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# the environment variables
[[ ! -v TERMINAL ]] && TERMINAL="kitty"
[[ ! -v BROWSER ]] && BROWSER="surf"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-open [-h] FILE/URL"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-open:"
  echo "     This script opens files and urls automatically."
  echo "     Do not forget to puth it in your PATH."
  echo ""
  echo "Usage:"
  echo "     amtoine-open [-h] FILE/URL"
  echo ""
  echo "Switches:"
  echo "     -h/--help       shows this help."
  echo ""
  echo "Environment variables:"
  echo "     TERMINAL        the terminal to use (defaults to 'kitty')"
  echo "     BROWSER         the browser to use (defaults to 'surf')"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help ) help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done
  [[ "$1" =~ http* ]] && { "$BROWSER" "$1"; exit 0; }

  [ -z "$ACTION" ] && usage
  case $(file --mime-type $1 -b) in
    text/*) $TERMINAL $EDITOR "$1";;
    image/*) feh $1;;
    */pdf) $TERMINAL okular "$1";;
    *) exit 1;;
  esac
}


main "$@"
