#! /usr/bin/bash
#*
#*                 _    __ _ _
#*  __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#* / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS: https://github.com/goatfiles
#* \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#* |___/
#*

export FZF_DEFAULT_OPTS='
--height=100%
--layout=reverse
--prompt="TL;DR: "
--preview="echo {1} | xargs -I{S} tldr {S} 2>/dev/null"'


help () {
  #
  # the help function.
  #
  echo "amtoine-wtldr:"
  echo "     This script allows the user to easily search tldr pages with fzf."
  echo "     Do not forget to puth it in your PATH."
  echo ""
  echo "     adapted from https://hiphish.github.io/blog/2020/05/31/macho-man-command-on-steroids"
  echo ""
  echo "Usage:"
  echo "     amtoine-wltdr [-h]"
  echo ""
  echo "Switches:"
  echo "     -h         show this help."
  exit 0
}


main () {
  #
  # TODO.
  #
  while getopts "h" opt; do
      case "$opt" in
          h ) help;;
          \?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
          : ) echo "Option -$OPTARG requires an argument" >&2; exit 1;;
      esac
  done

  help=$(
    tldr -l | \
    tr , '\n' | \
    sed "s/'//g; s/'//; s/\[//; s/\]//; s/ //g" | \
    sort | \
    fzf
  )
  [ -z "$help" ] && exit 0
  tldr "$help"
}


main "$@"
