#!/usr/bin/bash

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-pdf' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v BASE ]] && BASE="$HOME"
[[ ! -v EXCLUDE ]] && EXCLUDE="$HOME/.cache"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-pdf [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-pdf:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     amtoine-pdf [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     BASE                  the path where to search \`.pdf\` files from (defaults to \"\$HOME\")"
  echo "     EXCLUDE               paths to exclude from the search (defaults to \"\$HOME/.cache\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  dunstify "pdf.sh" "pulling pdfs from:\n'$BASE'\nexcluding:\n'$EXCLUDE'"
  choices=$(find "$BASE" -type f -name "*\.pdf" -not -path "$EXCLUDE/*" | dmenu -c -l 10 -bw 5 -p "Choose a pdf:" | sort -u)
  [ ! "$choices" ] && { echo -e "User choose to exit"; exit 1; }
  okular $choices
}


main "$@"
