#!/usr/bin/env bash
#*
#*                 _    __ _ _
#*  __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#* / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS: https://github.com/goatfiles
#* \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#* |___/
#*

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-weather-get' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v ICONS ]] && ICONS="/usr/share/icons/amtoine-icons-git/stickers/100x100"
[[ ! -v PLACES ]] && PLACES="Paris,Seoul,Nantes"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-weather-get [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-weather-get :"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     amtoine-weather-get [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     ICONS                 TODO (defaults to \"/usr/share/icons/amtoine-icons-git/dark/128x128\")"
  echo "     PLACES                TODO (defaults to \"Paris,Seoul,Nantes\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  notify-send -t 4500 "$(curl -s "wttr.in/{$PLACES}?format=3")" --icon="$ICONS/misc/partly-cloudy-day.png"
}


main "$@"
