#! /usr/bin/bash
#*
#*                 _    __ _ _
#*  __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#* / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS: https://github.com/goatfiles
#* \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#* |___/
#*          MAINTAINERS:
#*              AMTOINE: https://github.com/amtoine antoine#1306 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB
#*              ATXR:    https://github.com/atxr    atxr#6214    AF97503EDC65A06845114630F00A52147514670B
#*

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-dmrun' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v DMWIDTH ]] && DMWIDTH=700
[[ ! -v DMHEIGHT ]] && DMHEIGHT=10
[[ ! -v DMCOLUMNS ]] && DMCOLUMNS=3
[[ ! -v DMLINES ]] && DMLINES=9
[[ ! -v DMBORDER ]] && DMBORDER=5


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-dmrun [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-dmrun:"
  echo "     a wrapper around dmenu_run, with some extra flags to make it prettier."
  echo ""
  echo "Usage:"
  echo "     amtoine-dmrun [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     DMWIDTH               the width of the \`dmenu\` window (defaults to 700)"
  echo "     DMHEIGHT              the height of the \`dmenu\` window (defaults to 10)"
  echo "     DMCOLUMNS             the number of columns in the \`dmenu\` window (defaults to 3)"
  echo "     DMLINES               the number of lines in the \`dmenu\` window (defaults to 9)"
  echo "     DMBORDER              the width of the border of the \`dmenu\` window (defaults to 5)"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  dmenu_run -g $DMCOLUMNS -l $DMLINES \
            -x $((960 - $DMWIDTH/2)) -y $((540 - ($DMLINES+1)*$DMHEIGHT/2)) \
            -z $DMWIDTH -h $DMHEIGHT -bw $DMBORDER -fn "mononoki Nerd Font-20"
}


main "$@"
