#!/usr/bin/env bash

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'amtoine-lcfg' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to modufy environment variables
[[ ! -v GIT_DIR ]] && GIT_DIR="$HOME/.dotfiles"
[[ ! -v WORK_TREE ]] && WORK_TREE="$HOME"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-lcfg [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-lcfg:"
  echo "     open the dotfiles *bare* \`git\` repository in \`lazygit\`."
  echo ""
  echo "Usage:"
  echo "     amtoine-lcfg [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     GIT_DIR               the path to the \`git\` directory, i.e. the bare equivalent of the \`.git\` directory (defaults to \"\$HOME/.dotfiles\")"
  echo "     WORK_TREE             the path to the working tree of the dotfiles, i.e. where the files are tracked (defaults to \"\$HOME\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help ) help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  /usr/bin/lazygit --git-dir="$GIT_DIR" --work-tree="$WORK_TREE"
}


main "$@"
