#! /usr/bin/bash
#           ___                       personal page: https://amtoine.github.io/ 
#      __ _|_  )_ _    ___   ___      github   page: https://github.com/amtoine 
#     / _` |/ /| ' \  |___| (_-<      my   dotfiles: https://github.com/amtoine/dotfiles 
#     \__,_/___|_||_|       /__/
#           ___                         _
#      __ _|_  )_ _ ___ ________ ____ _| |
#     / _` |/ /| ' \___(_-<___\ \ / _` | |
#     \__,_/___|_||_|  /__/   /_\_\__,_|_|
#
# Description:  wraps the xautolock command with some notifications.
# Dependencies: xautolock, dunst
# License:      https://github.com/amtoine/scripts/blob/main/LICENSE
# Contributors: Stevan Antoine

# parse the arguments
OPTIONS=$(getopt -o hedn --long help,nable,disable,notify \
              -n 'amtoine-xal' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# environment variables
[[ ! -v ICONS ]] && ICONS="/usr/share/icons/amtoine-icons-git/stickers/100x100"


usage () {
  #
  # the usage function.
  #
  echo "Usage: amtoine-xal [-hedn]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "amtoine-xal:"
  echo "     This script allows the user to easily toggle xautolock."
  echo "     Do not forget to puth it in your PATH."
  echo ""
  echo "Usage:"
  echo "     amtoine-xal [-hedn]"
  echo ""
  echo "Switches:"
  echo "     -h/--help               shows this help."
  echo "     -e/--enable             enable the xautolock"
  echo "     -d/--disable            disable the xautolock"
  echo "     -n/--notify             enable notifications"
  echo ""
  echo "Environment variables:"
  echo "     ICONS                   the path the the icons (defaults to '/usr/share/icons/amtoine-icons-git/dark/128x128')"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )      help ;;
      -e | --enable)   ACTION="enable"; shift 1 ;;
      -d | --disable ) ACTION="disable"; shift 1 ;;
      -n | --notify )  NOTIFY="yes"; shift 1 ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done
  [ -z "$ACTION" ] && usage
  case "$ACTION" in
    disable ) xautolock -disable; [[ "$NOTIFY" == "yes" ]] && dunstify "amtoine-xal" "xautolock disabled" --icon="$ICONS/lock/padlock.png" ;;
    enable) xautolock -enable; [[ "$NOTIFY" == "yes" ]] && dunstify "amtoine-xal" "xautolock enabled" --icon="$ICONS/lock/lock.png" ;;
    * ) echo "an error occured (got unexpected '$ACTION')" ;;
  esac
}


main "$@"
