#! /usr/bin/bash
#*
#*                 _    __ _ _
#*  __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#* / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS: https://github.com/goatfiles
#* \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#* |___/
#*          MAINTAINERS:
#*              AMTOINE: https://github.com/amtoine antoine#1306 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB
#*              ATXR:    https://github.com/atxr    atxr#6214    AF97503EDC65A06845114630F00A52147514670B
#*

# parse the arguments.
OPTIONS=$(getopt -o h --long help -n 'amtoine-pedit' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# the environment variables
[[ ! -v DMFONT ]] && DMFONT="mononoki Nerd Font-20"
[[ ! -v PEDITOR ]] && PEDITOR="emacs"


help () {
  #
  # the help function.
  #
  echo "amtoine-pedit:"
  echo "     This script searches and edits \`pass\` entries."
  echo "     Do not forget to puth it in your PATH."
  echo ""
  echo "Usage:"
  echo "     amtoine-pedit [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help       shows this help."
  echo ""
  echo "Environment variables:"
  echo "     DMFONT        the font to user for \`dmenu\` (defaults to 'mononoki Nerd Font-20')"
  echo "     PEDITOR       the text editor to use (defaults to 'emacs')"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help ) help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  pass_entry=$(
    find ~/.password-store/ -type f -not -path "*/.git*" | \
    sed "s|$HOME\/\.password-store||; s/\.gpg//" | \
    dmenu -c -l 10 -bw 5 -p "Please choose a pass entry to edit:" -fn "$DMFONT"
  )
  [ -z "$pass_entry" ] && exit 0

  EDITOR="$PEDITOR" pass edit "$pass_entry"
}


main "$@"
