#!/bin/sh

set -e

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'glf' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"


lfrun () {
  #
  # TODO.
  #
  if [ -n "$DISPLAY" ]; then
    export FIFO_UEBERZUG="${TMPDIR:-/tmp}/lf-ueberzug-$$"

    cleanup() {
      exec 3>&-
      rm "$FIFO_UEBERZUG"
    }

    mkfifo "$FIFO_UEBERZUG"
    ueberzug layer -s <"$FIFO_UEBERZUG" &
    exec 3>"$FIFO_UEBERZUG"
    trap cleanup EXIT

    if ! [ -d "$HOME/.cache/lf" ]; then
      mkdir -p "$HOME/.cache/lf"
    fi

    lf "$@" 3>&-
  else
    exec lf "$@"
  fi
}


usage () {
  #
  # the usage function.
  #
  echo "Usage: glf [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "glf:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     glf [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  lfrun "$@"
}


main "$@"
