#! /usr/bin/bash

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'goat-tcfg' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# allow the user to change the environment variables.
[[ ! -v GIT_DIR ]] && GIT_DIR="$HOME/.dotfiles"
[[ ! -v WORK_TREE ]] && WORK_TREE="$HOME"


usage () {
  #
  # the usage function.
  #
  echo "Usage: goat-tcfg [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "goat-tcfg:"
  echo "     TODO."
  echo ""
  echo "Usage:"
  echo "     goat-tcfg [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  echo ""
  echo "Environment variables:"
  echo "     GIT_DIR               the path to the \`git\` directory, i.e. the bare equivalent of the \`.git\` directory (defaults to \"\$HOME/.dotfiles\")"
  echo "     WORK_TREE             the path to the working tree of the dotfiles, i.e. where the files are tracked (defaults to \"\$HOME\")"
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  GIT_DIR="$GIT_DIR" GIT_WORK_TREE="$WORK_TREE" tig --all
}


main "$@"
