#!/bin/bash
#*
#*                 _    __ _ _
#*  __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#* / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS: https://github.com/goatfiles
#* \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#* |___/
#*          MAINTAINERS:
#*              AMTOINE: https://github.com/amtoine antoine#1306 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB
#*              ATXR:    https://github.com/atxr    atxr#6214    AF97503EDC65A06845114630F00A52147514670B
#*

# parse the arguments
OPTIONS=$(getopt -o ah --long audio,help -n 'gvdl' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"

# environment variables
[[ ! -v QUALITY ]] && QUALITY="480"


usage () {
  #
  # the usage function.
  #
  echo "Usage: gvdl [-a] URL"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "gvdl:"
  echo "     This script allows the user to easily download videos from youtube.com"
  echo "     Do not forget to puth it in your PATH."
  echo ""
  echo "Usage:"
  echo "     gvdl [-a] URL"
  echo ""
  echo "Switches:"
  echo "     -h/--help               shows this help."
  echo "     -a/--audio              download the audio only"
  echo ""
  echo "Environment variables:"
  echo "     QUALITY                 the quality of the video to be downloaded (defaults to '480')"
  exit 0
}


main () {
  #
  # TODO.
  #
  ACTION="video"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )      help ;;
      -a | --audio )     ACTION="audio"; shift 1 ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done
  [ -z "$1" ] && usage
  case "$ACTION" in
    audio )  youtube-dl --format "bestaudio[ext=m4a]" --extract-audio "$1" ;;
    video )  youtube-dl --format "bestvideo[ext=mp4][height<=?$QUALITY]+bestaudio[ext=m4a]" "$1" ;;
    * ) echo "an error occured (got unexpected '$ACTION')"; exit 1 ;;
  esac
}


main "$@"
