#! /usr/bin/bash
#*
#*                 _    __ _ _
#*  __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#* / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS: https://github.com/goatfiles
#* \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#* |___/
#*          MAINTAINERS:
#*              AMTOINE: https://github.com/amtoine antoine#1306 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB
#*              ATXR:    https://github.com/atxr    atxr#6214    AF97503EDC65A06845114630F00A52147514670B
#*

# parse the arguments
OPTIONS=$(getopt -o h --long help -n 'gwvenv' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$OPTIONS"


usage () {
  #
  # the usage function.
  #
  echo "Usage: gwvenv [-h]"
  echo "Type -h or --help for the full help."
  exit 0
}


help () {
  #
  # the help function.
  #
  echo "gwvenv:"
  echo "     TODO."
  echo ""
  echo "     an example when not inside a virtual environment."
  echo "           command |                    path (version)"
  echo "          ---------+-------------------------------------------------------"
  echo "           python  | /usr/bin/python (Python 3.9.9)"
  echo "              pip  | /usr/bin/pip (pip 20.3.4)"
  echo "          python3  | /usr/bin/python3 (Python 3.9.9)"
  echo "             pip3  | /usr/bin/pip3 (pip 20.3.4)"
  echo "          jupyter  | --"
  echo "          notebook | -- (--)"
  echo ""
  echo "     an example when inside a virtual environement, with jupyter installed."
  echo "           command |                    path (version)"
  echo "          ---------+-------------------------------------------------------"
  echo "           python  | /home/ants/.venvs/ml/bin/python (Python 3.9.9)"
  echo "              pip  | /home/ants/.venvs/ml/bin/pip (pip 21.3.1)"
  echo "          python3  | /home/ants/.venvs/ml/bin/python3 (Python 3.9.9)"
  echo "             pip3  | /home/ants/.venvs/ml/bin/pip3 (pip 21.3.1)"
  echo "          jupyter  | /home/ants/.venvs/ml/bin/jupyter"
  echo "          notebook | /home/ants/.venvs/ml/bin/jupyter-notebook (6.4.6)"
  echo ""
  echo "Usage:"
  echo "     gwvenv [-h]"
  echo ""
  echo "Switches:"
  echo "     -h/--help             shows this help."
  exit 0
}


main () {
  #
  # TODO.
  #
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h | --help )   help ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  if command -v python &> /dev/null; then
      PY=$(which python)
      PYV=$(python --version)
  fi
  if command -v pip &> /dev/null; then
      PIP=$(which pip)
      PIPV=$(pip --version | cut -d' ' -f1-2)
  fi
  if command -v python3 &> /dev/null; then
      PY3=$(which python3)
      PIP3=$(which pip3)
  fi
  if command -v pip3 &> /dev/null; then
      PY3V=$(python3 --version)
      PIP3V=$(pip3 --version | cut -d' ' -f1-2)
  fi
  JPT="--"
  if command -v jupyter &> /dev/null; then
      JPT=$(which jupyter)
  fi
  NB="--"
  NBV="--"
  if command -v jupyter-notebook &> /dev/null; then
      NB=$(which jupyter-notebook)
      NBV=$(jupyter-notebook --version)
  fi



  echo " command |                    path (version)"
  echo "---------+-------------------------------------------------------"
  echo " python  | $PY ($PYV)"
  echo "    pip  | $PIP ($PIPV)"
  echo "python3  | $PY3 ($PY3V)"
  echo "   pip3  | $PIP3 ($PIP3V)"
  echo "jupyter  | $JPT"
  echo "notebook | $NB ($NBV)"
}


main "$@"
