#!/usr/bin/env bash

choice=$(echo "$@" | tr ' ' '\n' | fzf)
if [[ -z $choice ]]; then
    exit 0
fi

name=$(basename "$choice" | tr . _)

tmux_running=$(pgrep tmux)
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $name -c $choice
    exit 0
fi

if ! tmux has-session -t=$name 2> /dev/null; then
    tmux new-session -ds $name -c $choice
fi

tmux switch-client -t $name
